#!/usr/bin/ruby
require 'optparse'

class BlogPoster
  def initialize()
    @title=nil
    @cover=nil
    @categories=nil
	end

	def optparsing()
		opt_parser = OptionParser.new do |opt|
			opt.on("-t", "--title [title]", String, "the post title name") do |v|
        @title = v
      end
      opt.on("-i", "--cover [image]", String, "image name under /images folder") do |v|
        @cover = v
      end
      opt.on("-c", "--categories [categories]", String, "The categories this post would be sort to") do |v|
        @categories = v
      end
    end

    opt_parser.parse!
  end

  def generate()
    # title is a necessary option
    unless @title
      puts "Please input the post titles"
      return
    end

    unless @categories
      @categories = 'unsorted'
    end

    full_date = Time.new.strftime("%Y-%m-%d %H:%M:%S")
    short_date = Time.new.strftime("%Y-%m-%d")
    post_name = "#{short_date}-#{@title.gsub(/\s/, '-')}.md"

    File.open("./_posts/#{post_name}", 'w') do |f|
      f.puts("---")
      f.puts("layout: post")
      f.puts("title: #{@title}")
      f.puts("cover: #{@cover}") if @cover
      f.puts("date: #{full_date}")
      f.puts("categories: #{@categories}")
      f.puts("---")
      f.puts("")
    end

    puts "new post \"#{post_name}\" is generated!"
  end
end

poster = BlogPoster.new
poster.optparsing
poster.generate
